AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  challenge-lambda-app

  Sample SAM Template for challenge-lambda-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetSongsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          BUCKET_NAME: challenge-bucket-bruno-cw
          BUCKET_KEY: songData.json
      CodeUri: getsongs/
      Handler: App.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 10
      Events:
        GetSongs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /songs
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetSongsApi:
    Description: "API Gateway endpoint URL for Prod stage for GetSongs function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/songs/"
  GetSongsFunction:
    Description: "GetSongs Lambda Function ARN"
    Value: !GetAtt GetSongsFunction.Arn
  GetSongsFunctionIamRole:
    Description: "Implicit IAM Role created for GetSongs function"
    Value: !GetAtt GetSongsFunctionRole.Arn
